### PR TITLE
Update to version 1.2.2

### PR DESCRIPTION
**Pull request by martinandersen**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by martinandersen** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
CI has some sort of version constraint issue that it looks you are on top of.

Other issue is `suitesparse` has not been rebuilt with the new compilers as it is blocked by `metis`, which lacks a rebuild PR currently ( https://github.com/conda-forge/metis-feedstock/issues/17 ).

**Comment by martinandersen** [comment]
@conda-forge-admin, please rerender

**Comment by martinandersen** [comment]
@conda-forge-admin, please rerender

**Comment by martinandersen** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
