### PR TITLE
MNT: Updated some of the pinned versions

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by jjhelmus** [comment]
This is a rebased of #8 onto the current master which has been re-rendered.

**Comment by jjhelmus** [comment]
Looks like suitesparse needs to be re-pinned before this will work.

**Comment by jjhelmus** [comment]
Updating pins of suitesparse: conda-forge/suitesparse-feedstock#13

**Comment by jakirkham** [comment]
Yeah, I had gotten `suitesparse` re-rendered, but hadn't had a chance to repin it yet. We need the `v4.4.6` branch of `suitesparse` updated for `cvxopt` as we can't use the latest version yet.

**Comment by jakirkham** [comment]
Thanks @jjhelmus .

**Comment by jjhelmus** [comment]
You must have been watching the build, that was one quick merge!  Thanks @jakirkham

**Comment by jakirkham** [comment]
I was. 😄 Thanks @jjhelmus .

**Pull request merged**
