### PR TITLE
Rebuild for pypy (redux)

### PR DESCRIPTION
**Pull request by h-vetinari**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Trying my hand at manually redoing #40 since the bot didn't pick up the rerun label. If that doesn't work with the migration, I'm happy to close it. @conda-forge/help-pypy

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by h-vetinari** [comment]
@conda-forge/help-pypy
Pypy is segfaulting during the test suite on linux/osx/ppc/aarch:

```
===== testing package: cvxopt-1.2.4-py36h39dc144_205 =====
running run_test.py
============================= test session starts ==============================
platform linux -- Python 3.6.9[pypy-7.3.1-final], pytest-5.3.5, py-1.8.1, pluggy-0.12.0
rootdir: $SRC_DIR
collected 39 items

Fatal Python error: Aborted

Stack (most recent call first, approximate line numbers):
  File "/home/conda/feedstock_root/build_artifacts/cvxopt_1586939485271/test_tmp/tests/test_basic.py", line 18 in test_basic
/home/conda/feedstock_root/build_artifacts/cvxopt_1586939485271/test_tmp/conda_test_runner.sh: line 2:   817 Aborted                 (core dumped) "/home/conda/feedstock_root/build_artifacts/cvxopt_1586939485271/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python" -s "/home/conda/feedstock_root/build_artifacts/cvxopt_1586939485271/test_tmp/run_test.py"
Tests failed for cvxopt-1.2.4-py36h39dc144_205.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING:conda_build.build:Tests failed for cvxopt-1.2.4-py36h39dc144_205.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING conda_build.build:tests_failed(2751): Tests failed for cvxopt-1.2.4-py36h39dc144_205.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
TESTS FAILED: cvxopt-1.2.4-py36h39dc144_205.tar.bz2
```

Investigating is unfortunately out of my league.

**Comment by mattip** [comment]
This is enough to trigger it:
```
        import cvxopt
        a = cvxopt.matrix([1.0,2.0,3.0])
        aa = list(a)  # segfaults
```

Still digging to see if this is something in `cvxopt.matrix` or PyPy

**Comment by h-vetinari** [comment]
Thanks for investigating!

**Comment by mattip** [comment]
It turns out cvxopt was not calling `PyType_Ready` on some of the user-defined types

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
ppc64le failures are only from lack of space on the worker (this has been happening a lot recently?). I don't have the rights to restart them for this feedstock.

**Comment by h-vetinari** [comment]
The good news is: Thanks to @mattip and @martinandersen, the segfaults on PyPy are gone. :)

**Comment by h-vetinari** [comment]
To whoever restarted the build: it worked :)

**Comment by jjhelmus** [comment]
LGTM, thanks @h-vetinari

**Pull request merged**
